name: 'Main Build'

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Read VERSION
        id: package
        uses: martinbeentjes/npm-get-version-action@master

      - name: Echo VERSION
        run: echo ${{ steps.package.outputs.current-version }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          context: .
          tags: antoinejaussoin/fivlet:latest,antoinejaussoin/fivlet:${{ steps.package.outputs.current-version }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
